dbmig/accounts/urls.py
from django.conf.urls import url
from accounts import views
from accounts.views import TransactionView, ReceiptView, AccountsCreate
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    # url(r'vduplicate',views.copy,name='copy'),
    url(r'voucher',views.TransactionView.as_view(), name='voucher'),
    url(r'receipt',views.ReceiptView.as_view(), name='receipt'),
    url(r'acchead',views.AccountsCreate.as_view(), name='acchead'),   
    url(r'dlt',views.vrdelete, name='delete'), 
    url(r'dplct',views.vrdata,name='dplct'),
    # url(r'^(?P<accountstransaction_id>[0-9]+)/delete_voucher/$', views.vrdelete, name='vchrdlt'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmig/app/urls.py
from django.conf.urls import url
from app import views
# from app.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


app_name = 'app'

urlpatterns = [
    url(r'lorry-receipt/', views.LorryReceiptView.as_view(), name='lr'),
    url(r'validate', views.validate, name='validate'),
    url(r'print/$', views.generate_pdf, name='print'),
    url(r'podc', views.LrdocumentCreate.as_view(), name= 'podc'),
    url(r'pod', views.pod, name= 'pod'),
    url(r'signin', views.sign_in,name='signin'),
    url(r'whm', views.WhmCreate.as_view(),name='whm'),
    url(r'^$',views.dash, name= 'dash'),
    url(r'register', views.register,name='register'),
    url(r'signout', views.LogoutView.as_view(),name='signout'),
    url(r'delete', views.deletelr,name='deletelr'),
    url(r'change', views.change,name='change'),
    url(r'duplicate', views.duplicate,name='duplicate'),
    url(r'editvno', views.editvno,name='editvno'),
    url(r'^(?P<i_id>[0-9]+)/$', views.pod_data, name='pod_data'),
    url(r'rreceipt', views.rreceipt, name= 'rreceipt')
    # url(r'delete_lr/$', views.delete_,name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmig/dbmig/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()
urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('app.urls')),
    url('accounts/', include('accounts.urls')),
    url('master/', include('master.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

dbmig/accounts/models.py
from django.db import models
from django.dispatch import receiver
from django.utils.timezone import now
from django.db.models.signals import pre_delete

# Create your models here.


# class Openingclosingbalance(models.Model):
#     # ocb_id = models.AutoField(primary_key=True)
#     ocb_date = models.DateField(blank=True, null=True)
#     ocb_opngbalnc = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
#     ocb_clsngbalnc = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
#     ocb_whmcode = models.IntegerField(blank=True, null=True)
#     ocb_opngdatetime = models.DateTimeField(blank=True, null=True)
#     ocb_opngusrid = models.IntegerField(blank=True, null=True)
#     ocb_clsngtime = models.DateTimeField(blank=True, null=True)
#     ocb_clsngusrid = models.IntegerField(blank=True, null=True)
#     ocb_status = models.CharField(max_length=1, blank=True, null=True)

#     # class Meta:
#     #     managed = False
#     #     db_table = 'openingclosingbalance'




class VoucherNumbersettings(models.Model):
    # vou_id = models.AutoField()
    vou_desc = models.CharField(max_length=50, blank=True, null=True)
    vou_no = models.CharField(max_length=10, blank=True, null=True)
    vou_wrhcodepntr = models.IntegerField(blank=True, null=True)
    vou_code = models.CharField(max_length=10, blank=True, null=True)
    vou_slno = models.IntegerField(blank=True, null=True)
    vou_active = models.CharField(max_length=1, blank=True, null=True)
    vou_remarks = models.CharField(max_length=250, blank=True, null=True)
    vou_clntcode = models.IntegerField(blank=True, null=True)
    vou_city = models.CharField(max_length=25, blank=True, null=True)
    
    def __str__(self):
        return str(self.vou_code)
    # class Meta:
    #     managed = False
    #     db_table = 'voucher_numbersettings'


class Accountstransactionlog(models.Model):
    # act_tranid = models.AutoField(primary_key=True)
    logact_tranno = models.CharField(max_length=50, blank=True, null=True)
    logact_reason = models.TextField(max_length=250)
    logact_userid = models.IntegerField(blank=True, null=True)
    logact_deltime = models.DateTimeField(blank=True, null=True )
    logact_lrno = models.TextField(blank=True, null=True)
    logact_whmcode = models.CharField(max_length = 10, blank=True, null=True)
    logact_acc_code = models.CharField(max_length=30, blank=True, null=True)
    logact_glcode = models.CharField(max_length=15, blank=True, null=True)
    logact_trandate = models.DateField(blank=True, null=True)
    logact_vrno = models.CharField(max_length = 20, blank=True, null=True)
    logact_trantype = models.CharField(max_length=1, blank=True, null=True)
    logact_month = models.CharField(max_length = 20, blank=True, null=True)
    logact_pay = models.TextField(blank=True, null=True)
    logact_cash_rcpt = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    logact_cash_pymnt = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    logact_transfer_rcpt = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    logact_transfer_pymnt = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    logact_narration = models.TextField(blank=True, null=True)
    logact_checkerid = models.IntegerField(blank=True, null=True)
    logact_makerid = models.IntegerField(blank=True, null=True)
    logact_makingtime = models.DateTimeField(blank=True, null=True)
    logact_checkingtime = models.DateTimeField(blank=True, null=True)


class Accountmaster(models.Model):

    acc_choices = (
        ('P', 'Payment'),
        ('R', 'Receipt'),
    )
    # acc_id = models.AutoField(primary_key=True)
    acc_name = models.CharField(max_length=200, blank=True, null=True)
    acc_shortname = models.CharField(max_length=10, blank=True, null=True)
    acc_category = models.CharField(choices = acc_choices, max_length=1, blank=True, null=True)
    acc_status = models.CharField(max_length=1, blank=True, null=True)
    acc_makerid = models.IntegerField(blank=True, null=True)
    acc_maketime = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.acc_name
    # class Meta:
    #     managed = False
    #     db_table = 'accountmaster'


class Accountswarehousemaster(models.Model):
    # accwm_id = models.AutoField(primary_key=True)
    accwm_desc = models.CharField(max_length=50, blank=True, null=True)
    accwm_name = models.CharField(max_length=150, blank=True, null=True)
    accwm_slno = models.IntegerField(blank=True, null=True)
    accwm_remarks = models.CharField(max_length=250, blank=True, null=True)
    accwm_active = models.CharField(max_length=2, blank=True, null=True)

    # class Meta:
    #     managed = False
    #     db_table = 'accountswarehousemaster'
    def __str__(self):
        return self.accwm_name
    

class Accountstransaction(models.Model):
    # act_tranid = models.AutoField(primary_key=True)

    Month_choices = (
            ('1', 'January'),
            ('2', 'February'),
            ('3', 'March'),
            ('4', 'April'),
            ('5', 'May'),                                                                                                                                    
            ('6', 'June'), 
            ('7', 'July'), 
            ('8', 'August'), 
            ('9', 'September'),
            ('10', 'October'),
            ('11', 'November'),
            ('12', 'December'),
        )
    act_tranno = models.CharField(max_length=50, blank=True, null=True)
    act_lrno = models.TextField(verbose_name = 'LR Number', blank=True, null=True)
    act_whmcode = models.ForeignKey(Accountswarehousemaster,blank=True, null=True, verbose_name = 'Warehouse',  on_delete = models.CASCADE)
    act_acc_code = models.ForeignKey(Accountmaster, verbose_name = 'Account Head',  on_delete = models.CASCADE)
    act_glcode = models.CharField(max_length=10, blank=True, null=True)
    act_trandate = models.DateField(blank=True, null=True)
    act_vrno = models.CharField(max_length = 20, blank=True, null=True, verbose_name = 'Voucher Number')
    act_trantype = models.CharField(max_length=1, blank=True, null=True)
    act_pay = models.CharField(max_length = 150, verbose_name = 'Pay To', blank=True, null=True)
    act_month = models.CharField(choices = Month_choices, max_length = 50, verbose_name = 'Expense For The Month')
    act_cash_rcpt = models.DecimalField(max_digits=18, default=0, decimal_places=2, verbose_name='Rupees', blank=True, null=True)
    act_cash_pymnt = models.DecimalField(max_digits=18, default=0, decimal_places=2, verbose_name = 'Rupees', blank=True, null=True)
    act_transfer_rcpt = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    act_transfer_pymnt = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    act_narration = models.TextField(verbose_name = 'Narration', blank=True, null=True)
    act_checkerid = models.IntegerField(blank=True, null=True)
    act_makerid = models.IntegerField(blank=True, null=True)
    act_makingtime = models.DateTimeField(blank=True, null=True, verbose_name='Voucher Date')
    act_checkingtime = models.DateTimeField(blank=True, null=True)
    act_balance = models.DecimalField(max_digits=18, decimal_places=2, default=0.00, verbose_name= 'Cash Balance')

    def save(self, *args, **kwargs):    
        # if not self.pk:  # object is being created, thus no primary key field yet
        self.act_balance -= self.act_cash_pymnt
        self.act_balance += self.act_cash_rcpt
        # self.act_vrno = '{}-{}'.format(self.foo_rel.foo_code, self.bar_code)
        super(Accountstransaction, self).save(*args, **kwargs)                                  

@receiver(pre_delete, sender=Accountstransaction)
def _pre_delete_receiver(sender, instance, **kwargs):
    # instance = Lrtransation.objects.get(id = 'id')
    # kwargs = model_to_dict(instance, exclude=['id','lrtran_driverdtls'])

    new_instance = Accountstransactionlog()

    new_instance.logact_tranno = instance.act_tranno
    new_instance.logact_lrno = instance.act_lrno
    new_instance.logact_whmcode = str(instance.act_whmcode)
    new_instance.logact_acc_code = instance.act_acc_code
    new_instance.logact_glcode = instance.act_glcode
    new_instance.logact_trandate = instance.act_trandate
    new_instance.logact_vrno = str(instance.act_vrno)
    new_instance.logact_trantype = instance.act_trantype
    new_instance.logact_month = instance.act_month
    new_instance.logact_pay = instance.act_pay
    new_instance.logact_cash_rcpt = instance.act_cash_rcpt
    new_instance.logact_cash_pymnt = instance.act_cash_pymnt
    new_instance.logact_transfer_rcpt = instance.act_transfer_rcpt
    new_instance.logact_transfer_pymnt = instance.act_transfer_pymnt
    new_instance.logact_narration = instance.act_narration
    new_instance.logact_checkerid = instance.act_checkerid
    new_instance.logact_makerid = instance.act_makerid
    new_instance.logact_makingtime = instance.act_makingtime
    new_instance.logact_checkingtime = instance.act_checkingtime

    new_instance.save()

dbmig/templates/base_4.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="img/favicon.png">

  <title>{% block title %}:: Dashboard ::{% endblock %}</title>
  {% load staticfiles %}
  <!-- Bootstrap CSS -->
  <link href="{% static 'app/css/bootstrap.min.css' %}" rel="stylesheet" >
  <!-- bootstrap theme -->
  <link href="{% static 'app/css/bootstrap-theme.css' %}" rel="stylesheet">
  <!--external css-->
  <!-- font icon -->
  <link href="{% static 'app/css/elegant-icons-style.css' %}" rel="stylesheet" >
  <link href="{% static 'app/css/font-awesome.min.css' %}" rel="stylesheet" >
  <!-- Custom styles -->
  <link href="{% static 'app/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'app/css/style-responsive.css' %}" rel="stylesheet" >

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
  <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
      <script src="{% static 'js/lte-ie7.js' %}"></script>
    <![endif]-->

</head>

<body>
  <!-- container section start -->
  <section id="container" class="">
    <!--header start-->

    <header class="header dark-bg">
      <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
      </div>

      <!--logo start-->
          <a href="{% url 'app:dash' %}"><img class = "logo" src="{% static 'logo.jpg' %}" /></a>
      <!--logo end-->

      <div class="top-nav notification-row">
        <!-- notificatoin dropdown start-->
        <ul class="nav pull-right top-menu">

          <!-- user login dropdown start-->
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="username">{{ user.username }}</span>
                            <b class="caret"></b>
                        </a>
            <ul class="dropdown-menu extended logout">
              <div class="log-arrow-up"></div>
              <li class="eborder-top">
                <a href="#"><i class="icon_profile"></i> My Profile</a>
              </li>
              <li>
                <a href="{% url 'app:signout' %}"><i class="icon_key_alt"></i> Log Out</a>
              </li>
            </ul>
          </li>
          <!-- user login dropdown end -->
        </ul>
        <!-- notificatoin dropdown end-->
      </div>
    </header>
    <!--header end-->

    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
          <li class="">
            <a class="" href="{% url 'app:dash' %}">
                          <i class="icon_house_alt"></i>
                          <span>Dashboard</span>
                      </a>
          </li>

          <li class="sub-menu ">
            <a href="javascript:;" class="">
                          <i class="icon_documents_alt"></i>
                          <span>Accounts</span>
                          <span class="menu-arrow arrow_carrot-right"></span>
                      </a>
            <ul class="sub">
              <li><a class="" href="{% url 'accounts:voucher' %}">Transactions</a></li>
                  <nav class="nav nav-pills flex-column">
                  <a class="nav-link ml-3" href={% url 'accounts:voucher' %}><small>Payment</small></a>
                  <a class="nav-link ml-3" href={% url 'accounts:receipt' %}><small>Receipt</small></a>
                  </nav>
              <li><a class="" href="{% url 'accounts:dplct' %}"><span>Utilites</span></a></li>
                  <nav class="nav nav-pills flex-column">
                  <a class="nav-link ml-3" href={% url 'accounts:delete' %}><small>Voucher Cancellation</small></a>
                  <a class="nav-link ml-3" href={% url 'accounts:dplct' %}><small>Duplicate Voucher</small></a>
                  <a class="nav-link ml-3" href={% url 'accounts:acchead' %}><small>Accounts Head Creator<small></a>
                  </nav>
              <li><a class="" href="{% url 'accounts:delete' %}"><span>Reports</span></a></li>
            </ul>
          </li>
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->
{% block content %}
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-12">
            <h3 style = "color: #fff" class="page-header"><i class="fa fa-tachometer"></i> Dashboard</h3>
          </div>
        </div>
        <!-- page start-->

<!-- <div class="card w-75">
  <div class="card-body">
    <h5 class="card-title">USER</h5>
    <p style = "color: #fff" class="card-text">Click here to create a user</p>
    <a href="#" class="btn btn-primary">Create User</a>
  </div>
</div>
<br>
<br> -->        
<br>
{% if request.user.is_superuser %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3 class="display-4">USER</h1>
    <p class="lead">Click here to create user</p>
    <a href="{% url 'app:register' %}" class="btn btn-primary">Create User</a>
  </div>
</div>
<br>

<!-- <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3 class="display-4">WAREHOUSE</h1>
    <p class="lead">Click here to create Warehouse</p>
    <a href="{% url 'app:whm' %}" class="btn btn-primary">Create Warehouse</a>
  </div>
</div> -->

{% endif %}
<br>

{% if request.user.is_superuser %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3 class="display-4">FLEET MANAGEMENT</h1>
      <br>
    <img class = "img-responsive" src="{% static 'fleet.png' %}" width = "1200" height="600">   
  </div>
</div>
{% endif %}

<!-- <div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">WAREHOUSE DASHBOARD</h5>
              <h4 style="color: #FFF">Select Warehouse:</h4>
               <select>
                <option value="">Whirlpool Sales Kochi</option>
                <option value="">Godrej Kochi</option>
                <option value="">Godrej Calicut</option>
                <option value="">Whirlpool Sales Banglore</option>
                <option value="">Godrej Branch Banglore</option>
                <option value="">Godrej Hub Banglore</option>
               </select> <br><br>
              <p class="">Quantity:</p>
  </div>
</div>
 -->
        <!-- page end-->
      </section>  
    </section>
    <!--main content end-->
  </section>
  <!-- container section end -->
  <!-- javascripts -->
  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'app/js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="{% static 'app/js/scripts.js' %}"></script>

  
{% endblock %}
</body>

</html>

dbmig/templates/duplicate.html
{% extends "dash.html" %}
{% block title %}::Duplicate Voucher Print::{% endblock %}
{% block transactions %}active{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
  <h2>Duplicate Voucher</h2>
  <br>
  <!-- Nav pills -->
  <ul class="nav nav-pills" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="pill" href="#home">Duplicate Voucher</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:delete' %}">Voucher cancellation</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:acchead' %}">Account Head Create</a>
    </li>
  </ul>


  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h2> Duplicate Voucher</h2>
                    <br>
                    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'accounts:duplicate' %}">
                        <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                        <button type="submit" class="btn btn-default">Find Voucher</button>
                </form>

                <br>
            <br>
            <br>
    </div>    
                <div class="row">
                <div class="col">
                    <div class="panel panel-default">

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Voucher number</th>
                                <th>Account head</th>
                                <th>To pay</th>
                                <th>Amount</th>
                                <th>Narration</th>
                                <th>Action<th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for voucher in voucher_list %}
                                <tr>
                                    <td>{{ voucher.act_vrno }}</td>
                                    <td>{{ voucheract_acc_code.acc_name }}</td>
                                    <td>{{ voucher.act_pay }}</td>
                                    <td>{{ voucher.act_narration }} </td>
                                    <td>
                                        <form action="{% url 'accounts:delete' voucher.id %}" onclick="return confirm('Are you sure you want to print this item?');" method="post" style="display: inline;">
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>      
              
  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'app/js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="{% static 'app/js/scripts.js' %}"></script>
    
<style>
h2
{
    color: #fff;
}
container
{
    width:500px;
    padding-top:100px;
    color: #fff;
}
</style>

{% endblock %}

dbmig/templates/podc.html
{% extends "dash.html" %}
{% block title %}::POD Closure::{% endblock %}
{% block transactions %}active{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

  {% block jquery %}
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
<script type='text/javascript'>
    // Call hideShow when page is loaded
    $(document).ready(function(){
        hideShow()
    })

    // call hideShow when the user clicks on the component_type dropdownlist
    $('#id_act_acc_code').click(function(){
        hideShow()
    });

function hideShow(){
    if(document.getElementById('id_act_acc_code').value == "1")
    {
        $('#id_act_lrno').show();
    }else
    {
        $('#id_act_lrno').hide();
    }
}
</script>
{% endblock %}




<div class = "display">
<form method="POST" action="{% url 'app:podc' %}">
    <h2 class="text-white mb-5">Purchase order closure</h2>
    {% csrf_token %}
    <br>
    Please upload the Proof of Delivery
    {{ form|crispy }}<br>
    Trip Status<select> 
      <option value="O">Open</option>
      <option value="C">Closed</option>
    </select>
    <br>
    <br>
    <br>
    <input style = "border-radius:6px;" type="submit" class="button-primary" value="Upload">
  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

</form>
</div>

    

              
  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'app/js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="{% static 'app/js/scripts.js' %}"></script>
    
<style>

form
{
    width:650px;
    padding-top:100px;
    padding-left:350px;    
    color: #fff;
}
</style>

{% endblock %}

dbmig/templates/poddisp.html
{% extends "dash.html" %}
{% block title %}::POD Closure::{% endblock %}
{% block transactions %}active{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


        <div class="container">
            <div class="row">
                <div class="col">
                    <h3 class="text-white mb-5">Purchase Order Closure</h3>
                    {% csrf_token %}
                    <br>
                    <br>
                    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'app:pod' %}">
                        <div class="form-group">
                        Trip number
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>                    
                    <br>
                    <br>
                </div>
            </div>
          </div>
        <br>
        <br>
        <div class ="container">
            <div class="row">
                <div class="col">
                    <div class="panel panel-default">

                    <table class="table">
                        <thead>
                            <tr>
                                <th>LR no</th>
                                <th>Consignee</th>
                                <th>Location</th>
                                <th>LR Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for lrdtls in lrdtls_list %}
                                <tr>
                                    <td><a href="{% url 'app:pod_data' playlist.id %}">{{ lrdtls.lrtran_waybillno }}</a></td>
                                    <td>{{ lrdtls.lrtran_consgnepntr.consgnem_name }}</td>
                                    <td>{{ lrdtls.lrtran_consgnepntr.consgnem_district }}</td>
                                    <td>{{ lrdtls.lrtran_tripstatus }} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
<!-- <form>
  <div class="row">
    <div class="col">
     Consignee:<input class="form-control-plaintext" type="text" placeholder="{{ user.username }} " readonly>
    </div>
    <br>
    <div class="col">
      Trip number:
      <input type="text" class="form-control" placeholder="Trip number:">
    </div>
  </div>
</form>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h6>Purchase order closure file</h6>
    <input type="file" name="myfile">
    <br>
p{
    padding-top:100px;
    padding-left:350px;  
}
    <button style = "border-radius: 6px; " type="submit">Upload</button>
  </form> -->
    

              
  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'app/js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="{% static 'app/js/scripts.js' %}"></script>
    
<style>
h3{
    padding-top:100px;
    color:#fff;
}
form
{
    width:250px;
    padding-top:100px;
    color: #fff;
}
</style>

{% endblock %}