dbmig/accounts/urls.py
from django.conf.urls import url
from accounts import views
from accounts.views import TransactionView, ReceiptView, AccountsCreate
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    # url(r'vduplicate',views.copy,name='copy'),
    url(r'voucher',views.TransactionView.as_view(), name='voucher'),
    url(r'receipt',views.ReceiptView.as_view(), name='receipt'),
    url(r'acchead',views.AccountsCreate.as_view(), name='acchead'),   
    url(r'dlt',views.vrdelete, name='delete'), 
    url(r'dplct',views.vrdata,name='dplct'),
    # url(r'^(?P<accountstransaction_id>[0-9]+)/delete_voucher/$', views.vrdelete, name='vchrdlt'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmig/app/urls.py
from django.conf.urls import url
from app import views
# from app.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


app_name = 'app'

urlpatterns = [
    url(r'lorry-receipt/', views.LorryReceiptView.as_view(), name='lr'),
    url(r'validate', views.validate, name='validate'),
    url(r'print/$', views.generate_pdf, name='print'),
    url(r'podc', views.LrdocumentCreate.as_view(), name= 'podc'),
    url(r'pod', views.pod, name= 'pod'),
    url(r'signin', views.sign_in,name='signin'),
    url(r'whm', views.WhmCreate.as_view(),name='whm'),
    url(r'^$',views.dash, name= 'dash'),
    url(r'register', views.register,name='register'),
    url(r'signout', views.LogoutView.as_view(),name='signout'),
    url(r'delete', views.deletelr,name='deletelr'),
    url(r'change', views.change,name='change'),
    url(r'duplicate', views.duplicate,name='duplicate'),
    url(r'editvno', views.editvno,name='editvno'),
    url(r'^(?P<i_id>[0-9]+)/$', views.pod_data, name='pod_data'),
    url(r'rreceipt', views.rreceipt, name= 'rreceipt')
    # url(r'delete_lr/$', views.delete_,name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmig/dbmig/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()
urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('app.urls')),
    url('accounts/', include('accounts.urls')),
    url('master/', include('master.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

dbmig/app/templates/app/lrcancel.html
{% extends "dash.html" %}
{% block title %}::LR cancellation::{% endblock %}
{% block transactions %}active{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}



        <div class="container">
        <div class = "row">
            <h2> LR Cancellation</h2>
                <br>
                <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'app:deletelr' %}">
                    <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                    <button type="submit" class="btn btn-default">Find LR</button>
                </form>
        </div>
        <br>
        <br>
        <br>

  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'app/js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="{% static 'app/js/scripts.js' %}"></script>
    
<style>
h2
{
    color: #fff;
    padding-top:100px;
}
container
{
    width:500px;
    padding-top:100px;
    color: #fff;
}

</style>

{% endblock %}

dbmig/app/templates/app/lrchange.html
{% extends "dash.html" %}
{% block title %}::LR Charges Editor::{% endblock %}
{% block transactions %}active{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h2>LR Charges Editor</h2>
                    <br>
                    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'app:change' %}">
                        <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                        <button type="submit" class="btn btn-default">Find LR</button>
                </form>

                <br>
            <br>
            <br>
    </div>    
            

  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'app/js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="{% static 'app/js/scripts.js' %}"></script>
    
<style>
h2
{
    color: #fff;
    padding-top:100px;
}
container
{
    width:500px;
    padding-top:100px;
    color: #fff;
}
</style>

{% endblock %}

dbmig/app/templates/app/lrduplct.html
{% extends "dash.html" %}
{% block title %}::LR Duplicate Print::{% endblock %}
{% block transactions %}active{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h2> Duplicate LR</h2>
                    <br>
                    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'app:duplicate' %}">
                        <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                        <button type="submit" class="btn btn-default">Find LR</button>
                </form>

                <br>
            <br>
            <br>
    </div>    
                <div class="row">
                <div class="col">
                    <div class="panel panel-default">

                    <table class="table">
                        <thead>
                            <tr>
                                <th>LR number</th>
                                <th>Account head</th>
                                <th>To pay</th>
                                <th>Amount</th>
                                <th>Narration</th>
                                <th>Action<th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for lr in lr_list %}
                                <tr>
                                    <td>{{ lr.act_vrno }}</td>
                                    <td>{{ lract_acc_code.acc_name }}</td>
                                    <td>{{ lr.act_pay }}</td>
                                    <td>{{ lr.act_narration }} </td>
                                    <td>
                                        <form action="{% url 'app:delete' lr.id %}" onclick="return confirm('Are you sure you want to print this item?');" method="post" style="display: inline;">
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>      
              
  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'app/js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="{% static 'app/js/scripts.js' %}"></script>
    
<style>
h2
{
    color: #fff;
    padding-top:100px;
}
container
{
    width:500px;
    padding-top:100px;
    color: #fff;
}
</style>

{% endblock %}

dbmig/app/templates/app/vehicleno.html
{% extends "dash.html" %}
{% block title %}::Vehicle Number Editor::{% endblock %}
{% block transactions %}active{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h2>Vehicle Number Editor</h2>
                    <br>
                    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'app:editvno' %}">
                        <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                        <button type="submit" class="btn btn-default">Enter Vehicle no.</button>
                </form>

                <br>
            <br>
            <br>
    </div>    
            

  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'app/js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="{% static 'app/js/scripts.js' %}"></script>
    
<style>
h2
{
    color: #fff;
    padding-top:100px;
}
container
{
    width:500px;
    padding-top:100px;
    color: #fff;
}
</style>

{% endblock %}